version: '3'

services:
  ## Workspace Utilities ##################################
  workspace:
    build:
      context: images/workspace
      args:
      - LARADOCK_PHP_VERSION=${PHP_VERSION}
      - PUID=${WORKSPACE_PUID}
      - PGID=${WORKSPACE_PGID}
      - NODE_VERSION=${WORKSPACE_NODE_VERSION}
    volumes:
    - ./images/workspace/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
    - "${WORKSPACE_SSH_PORT}:22"
    tty: true
    environment:
    - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
    - frontend
    - backend

  ### PHP-FPM ##############################################
  php-fpm:
    build:
      context: images/php-fpm
      args:
      - LARADOCK_PHP_VERSION=${PHP_VERSION}
      - ADDITIONAL_LOCALES=${PHP_FPM_ADDITIONAL_LOCALES}
    volumes:
    - ./images/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    - ./images/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    environment:
    - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    - FAKETIME=${PHP_FPM_FAKETIME}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - APP_ENV=${LARAVEL_APP_ENV}
    - APP_DEBUG=${LARAVEL_APP_DEBUG}
    - APP_URL=${LARAVEL_APP_URL}
    depends_on:
    - workspace
    networks:
    - backend

  ### NGINX Server #########################################
  nginx:
    build:
      context: images/nginx
      args:
      - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
      - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    volumes:
    - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
    - "${NGINX_HOST_HTTP_PORT}:80"
    - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
    - php-fpm
    networks:
    - frontend
    - backend


  ### PostgreSQL ###########################################
  postgres:
    build: images/postgres
    volumes:
    - ${DATA_PATH_HOST}/.postgres:/var/lib/postgresql/data
    ports:
    - "${POSTGRES_PORT}:5432"
    environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
    - backend

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  postgres:
    driver: ${VOLUMES_DRIVER}